version: '3'

services:
  web:
    build: .
    command: gunicorn House_renting.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
