# Generated by Django 4.2.1 on 2023-08-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_project', '0002_remove_house_image_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
