# Generated by Django 4.2.1 on 2023-08-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_project', '0004_house_house_host_alter_house_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
