# Generated by Django 4.2.1 on 2023-08-16 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_project', '0006_house_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='House_guest',
        ),
    ]
